"""Domain models and errors for the new auth/session core."""

from .api_errors import (
    ApiDomainError,
    BackendUnavailable,
    ChallengeExpired,
    ChallengeRequired,
    InvalidCredentials,
    InvalidSecurityCode,
    QueryExecutionFailed,
    Unauthorized,
    UnsupportedQueryMode,
)
from .api_models import AuthPrincipal
from .auth_flow import AuthFlowError, AuthFlowRequest, AuthFlowResult, AuthStep, SecurityCodeRequired
from .service_contracts import (
    AccountDeviceDTO,
    AccountFamilyMemberDTO,
    AccountStorageDTO,
    AccountStorageMediaUsageDTO,
    AccountStorageUsageDTO,
    CalendarDTO,
    CalendarEventDetailDTO,
    CalendarEventDTO,
    ContactDTO,
    ContactEmailDTO,
    ContactPhoneDTO,
    DeviceRecordDTO,
    DriveNodeChildDTO,
    DriveNodeDTO,
    PhotoAlbumDTO,
    PhotoAssetDTO,
    PhotoVersionDTO,
    ReminderDTO,
    ReminderListsDTO,
    UbiquityNodeDTO,
)

__all__ = [
    "ApiDomainError",
    "AuthPrincipal",
    "AuthFlowError",
    "AuthFlowRequest",
    "AuthFlowResult",
    "AuthStep",
    "BackendUnavailable",
    "AccountDeviceDTO",
    "AccountFamilyMemberDTO",
    "AccountStorageDTO",
    "AccountStorageMediaUsageDTO",
    "AccountStorageUsageDTO",
    "ChallengeExpired",
    "ChallengeRequired",
    "CalendarDTO",
    "CalendarEventDTO",
    "CalendarEventDetailDTO",
    "ContactDTO",
    "ContactEmailDTO",
    "ContactPhoneDTO",
    "DeviceRecordDTO",
    "DriveNodeChildDTO",
    "DriveNodeDTO",
    "InvalidCredentials",
    "InvalidSecurityCode",
    "PhotoAlbumDTO",
    "PhotoAssetDTO",
    "PhotoVersionDTO",
    "QueryExecutionFailed",
    "ReminderDTO",
    "ReminderListsDTO",
    "SecurityCodeRequired",
    "UnsupportedQueryMode",
    "Unauthorized",
    "UbiquityNodeDTO",
]
