name: "Packaging Test"

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  check_packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
      - name: Build and Check Package
        run: |
          uv run --with build --with twine python -m build
          uv run --with twine twine check dist/*
